from typing import Protocol


class KeyProtectionService(Protocol):
    def wrap_content_key(self, context: dict, ck: bytes): ...
    def unwrap_content_key(self, record) -> bytes: ...
    def current_key_version(self) -> int: ...

