CREATE DOMAIN r3_control.bytes20 AS bytea CHECK (octet_length(VALUE) = 20);
CREATE DOMAIN r3_control.bytes32 AS bytea CHECK (octet_length(VALUE) = 32);
CREATE TYPE r3_control.job_status AS ENUM (
 'PENDING','CLAIMED','CANDIDATE_STORED','READY_FOR_CHAIN_COMMIT',
 'COMMIT_UNKNOWN','COMMITTED','RETRY_WAIT','FAILED_TERMINAL','DEAD_LETTER'
);
CREATE TYPE r3_control.header_status AS ENUM (
 'CANDIDATE','STORED','READY_FOR_CHAIN_COMMIT','COMMITTED','SUPERSEDED','FAILED'
);
CREATE TYPE r3_control.commit_status AS ENUM (
 'PREPARED','BROADCAST_UNKNOWN','CONFIRMED_TEST_DOUBLE','FAILED_TEST_DOUBLE'
);
