from enum import Enum


class HeaderErrorCode(str, Enum):
    INVALID_JSON = "INVALID_JSON"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    MISSING_FIELD = "MISSING_FIELD"
    DUPLICATE_FIELD = "DUPLICATE_FIELD"
    INVALID_SCHEMA_VERSION = "INVALID_SCHEMA_VERSION"
    UNSUPPORTED_SUITE = "UNSUPPORTED_SUITE"
    INVALID_CHAIN_ID = "INVALID_CHAIN_ID"
    INVALID_CONTRACT_ADDRESS = "INVALID_CONTRACT_ADDRESS"
    INVALID_RESOURCE_ID = "INVALID_RESOURCE_ID"
    INVALID_BODY_REFERENCE = "INVALID_BODY_REFERENCE"
    BODY_DIGEST_MISMATCH = "BODY_DIGEST_MISMATCH"
    INVALID_POLICY_DIGEST = "INVALID_POLICY_DIGEST"
    EPOCH_MISMATCH = "EPOCH_MISMATCH"
    STATE_VERSION_MISMATCH = "STATE_VERSION_MISMATCH"
    HEADER_VERSION_MISMATCH = "HEADER_VERSION_MISMATCH"
    BODY_VERSION_MISMATCH = "BODY_VERSION_MISMATCH"
    KEY_VERSION_MISMATCH = "KEY_VERSION_MISMATCH"
    KEY_BODY_VERSION_MISMATCH = "KEY_BODY_VERSION_MISMATCH"
    UPDATE_KIND_MISMATCH = "UPDATE_KIND_MISMATCH"
    BODY_DIGEST_TRANSITION_INVALID = "BODY_DIGEST_TRANSITION_INVALID"
    PREVIOUS_HEADER_DIGEST_MISMATCH = "PREVIOUS_HEADER_DIGEST_MISMATCH"
    RECIPIENT_LIST_EMPTY = "RECIPIENT_LIST_EMPTY"
    RECIPIENT_DUPLICATE = "RECIPIENT_DUPLICATE"
    RECIPIENT_ORDER_INVALID = "RECIPIENT_ORDER_INVALID"
    RECIPIENT_NOT_FOUND = "RECIPIENT_NOT_FOUND"
    USER_VERSION_MISMATCH = "USER_VERSION_MISMATCH"
    HPKE_CONTEXT_MISMATCH = "HPKE_CONTEXT_MISMATCH"
    HPKE_OPEN_FAILED = "HPKE_OPEN_FAILED"
    HEADER_DIGEST_MISMATCH = "HEADER_DIGEST_MISMATCH"
    ISSUER_KEY_ID_MISMATCH = "ISSUER_KEY_ID_MISMATCH"
    HEADER_SIGNATURE_INVALID = "HEADER_SIGNATURE_INVALID"
    HEADER_OBJECT_CORRUPT = "HEADER_OBJECT_CORRUPT"
    BODY_OBJECT_CORRUPT = "BODY_OBJECT_CORRUPT"
    UNTRUSTED_HEADER = "UNTRUSTED_HEADER"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class HeaderValidationError(ValueError):
    def __init__(self, code: HeaderErrorCode):
        self.code = code
        super().__init__(code.value)
